// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo.Infra.Data.Contexto;

namespace Modelo.Infra.Data.Migrations
{
    [DbContext(typeof(ApiContexto))]
    [Migration("20190628130903_VersaoBanco_001")]
    partial class VersaoBanco_001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelo.Domain.Entidades.CadastrosIniciais.Estado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("BIGINT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<long>("Pais_Id");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("VARCHAR(2)");

                    b.Property<DateTime>("TimesTamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("TimesTamp")
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Pais_Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Modelo.Domain.Entidades.CadastrosIniciais.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Codigo")
                        .HasColumnType("VARCHAR(10)")
                        .HasDefaultValue("");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Observacoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Observacoes")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("TimesTamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("TimesTamp")
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Modelo.Domain.Entidades.CadastrosIniciais.Estado", b =>
                {
                    b.HasOne("Modelo.Domain.Entidades.CadastrosIniciais.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("Pais_Id")
                        .HasConstraintName("Fk_Estado_Pais")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
